version: '3.9'

networks:
    jenkins:
        driver: bridge

services:
#    docker:
#        image: docker:dind
#        networks:
#            - jenkins
#        environment:
#            DOCKER_TLS_CERTDIR: /certs
#        volumes:
#            - ./jenkins-docker-certs:/certs/client
#            - ./jenkins-data:/var/jenkins_home
#        ports:
#            - 2376:2376

    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            - 50000:50000
        networks:
            - jenkins
        volumes:
            - ./jenkins-data:/var/jenkins_home
#            - /var/run/docker.sock:/var/run/docker.sock
#            - ./jenkins-docker-certs:/certs/client:ro
#        environment:
#            DOCKER_TLS_VERIFY: 1
#            DOCKER_CERT_PATH: /certs/client
#            DOCKER_HOST: tcp://docker:2376
