version: '3.9'

networks:
    jenkins:
        driver: bridge

services:
    ubuntu-desktop:
        image: dorowu/ubuntu-desktop-lxde-vnc
        ports:
            - 3000:80
    docker:
        image: docker:dind
        privileged: true
        networks:
            - jenkins
        environment:
            DOCKER_TLS_CERTDIR: /certs
        volumes:
            - ./jenkins-docker-certs:/certs/client
            - ./jenkins-data:/var/jenkins_home
        storage-driver:
            overlay2
    jenkins:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:8080
            - 50000:50000
        networks:
            - jenkins
        volumes:
            - ./jenkins-data:/var/jenkins_home
            - ./jenkins-docker-certs:/certs/client
        environment:
            DOCKER_TLS_VERIFY: 1
            DOCKER_TLS_CERTDIR: /certs
            DOCKER_CERT_PATH: /certs/client
            DOCKER_HOST: tcp://docker:2376
